apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: riot-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lolanalytics/riot-gateway.git'
    path: .deployment
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
